name: AWS OIDC Test

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest

    steps:

      - name: Check OIDC environment
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL exists:"
          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "YES"
          else
            echo "NO"
          fi

          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN exists:"
          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
            echo "YES"
          else
            echo "NO"
          fi